ignoreFiles = ["\\.org$"]
baseURL = 'https://blog.tsono.org'
languageCode = 'ja'
title = 'tsono blog'
theme = "my-high-contrast-theme"
enableGitInfo = true
defaultContentLanguage = 'ja'
defaultContentLanguageInSubdir = true



[services]
  [services.disqus]
    shortname = 'blog-tsono'

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
  [languages.ja]
    languageName = "Japanese"
    weight = 20

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  tag = "tags"

#[permalinks]
#  tags = "/tags/:slug/"
#  categories = "/categories/:slug/"
#  posts = "/posts/:year/:month/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[pagination]
  pagerSize = 10

[params]
  # To disable remote fetching for link cards, set enableLinkCardRemoteFetch to false.
  # This can be useful for local or offline builds.
  # enableLinkCardRemoteFetch = false
  mainSections = ["posts"]
  toc = true
  favicon = "/favicon.ico"
  description = ""
  customCSS = ["css/custom.css"]

  [params.dateFormat]
    published = "2006-01-02"

  [params.author]
    name = "tsono"
    image = "/images/profile.png"

  [params.comments]
    enabled = true

[params.comments.giscus]
  repo = "tsonobe1/hugo-tsono"
  repoID = "R_kgDOPDr9kw"
  category = "General"
  categoryID = "DIC_kwDOPDr9k84CsOK_"
  mapping = "issue-term"
  strict = false
  reactionsEnabled = true
  emitMetadata = false
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  
  loading = "lazy"

  [params.social]
    github = "https://github.com/tsonobe1"
    twitter = "https://twitter.com/tsonobe_"

  #  googleAnalytics = "G-DDY3NMJKLW"

[security]
  [security.http]
    methods = ["GET", "POST"]
    urls = [".*"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    # lineNos = true
    style = "github"
    # lineNumbersInTable = true

ignoreFiles = ["\\.org$"]