baseURL = 'https://blog.tsono.org'
languageCode = 'ja'
title = 'tsono blog'
theme = "my-high-contrast-theme"
defaultContentLanguage = 'ja'
ignoreFiles = ["\\.org$"]

[languages]
  ja = { title = "tsono blog", languageName = "Japanese", weight = 10 }
  en = { title = "tsono blog", languageName = "English", weight = 20 }

[taxonomies]

  category = "categories"
  tag = "tags"

[permalinks]
  tags = "/tags/:slug/"
  categories = "/categories/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[pagination]
  pagerSize = 10

[params]
  # To disable remote fetching for link cards, set enableLinkCardRemoteFetch to false.
  # This can be useful for local or offline builds.
  # enableLinkCardRemoteFetch = false
  mainSections = ["posts"]
  toc = true
  favicon = "/favicon.ico"
  description = ""
  customCSS = ["css/custom.css"]

  [params.dateFormat]
    published = "2006-01-02"

  [params.author]
    name = "tsono"
    image = "/images/profile.png"

  [params.comments]
    enabled = true
    provider = "giscus"

[params.comments.giscus]
  repo = "tsonobe1/hugo-tsono"
  repoID = "R_kgDOPDr9kw"
  category = "General"
  categoryID = "DIC_kwDOPDr9k84CsOK_"
  mapping = "issue-term"
  strict = false
  reactionsEnabled = true
  emitMetadata = false
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "ja"
  loading = "lazy"

  [params.social]
    github = "https://github.com/tsonobe1"
    twitter = "https://twitter.com/tsonobe_"

  googleAnalytics = "G-DDY3NMJKLW"

[security]
  [security.http]
    methods = ["GET", "POST"]
    urls = [".*"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true