baseURL = 'https://blog.tsono.org'
languageCode = 'ja'
title = 'tsono blog'
theme = "my-high-contrast-theme"
defaultContentLanguage = 'ja'

ignoreFiles = ["\\.org$"]

[taxonomies]

  category = "categories"
  tag = "tags"

[permalinks]
  tags = "/tags/:slug/"
  categories = "/categories/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]
  toc = true
  favicon = "/favicon.ico"
  description = ""
  customCSS = ["css/custom.css"]

  [params.dateFormat]
    published = "2006-01-02"

  [params.author]
    name = "tsonobe"
    image = "/images/profile.png"

  [params.comments]
    enabled = true
    provider = "giscus"

[params.comments.giscus]
  repo = "tsonobe1/hugo-tsono"
  repoID = "R_kgDOPDr9kw"
  category = "General"
  categoryID = "DIC_kwDOPDr9k84CsOK_"
  mapping = "pathname"
  strict = false
  reactionsEnabled = true
  emitMetadata = false
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "ja"
  loading = "lazy"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true